version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "linebot-1201"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r7y7c5yb0kz"
s3_prefix = "linebot-1201"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LineChannelAccessToken=\"ewn51EIp4C3aDyrw0kVe9CwhsxZwf60+Ls2kVl1GraqbgxzEAO2dOYjd3Vv4tQXlsTKi1aGvZPiTKFNJJdHxnFizsjIgtA4awFE0Nh0EGHJEH5JQsneGq9Xpg8CGBMnUgC3eovgWGRAeDng5sz1nSgdB04t89/1O/w1cDnyilFU=\" LineChannelSecret=\"b749f3f88a82613eeebfb4c8a997500b\""
